<?php

namespace UserBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function findByRole($role)
	{
		$qb = $this->createQueryBuilder('u');
		$qb->select('u')
		   ->leftJoin('u.groups', 'g')
		   ->where($qb->expr()->orX(
			   $qb->expr()->like('u.roles', ':roles'),
			   $qb->expr()->like('g.roles', ':roles')
		   ))
		   ->setParameter('roles', '%"'.$role.'"%');

		return $qb->getQuery()->getResult();
	}
}
