<?php

namespace BirdBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * TaxrefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxrefRepository extends EntityRepository
{
    public function findBirdName($bird)
    {
        return $this->createQueryBuilder('taxref')
            ->andWhere('taxref.nomVern = :nomVern')
            ->setParameter('nomVern', $bird)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
