<?php

namespace BirdBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * TaxrefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxrefRepository extends EntityRepository
{
    public function findBirdName()
    {
        return $this->createQueryBuilder('taxref')
	        ->addOrderBy('taxref.nomVern', 'ASC')
            ->getQuery()
            ->getResult();
    }
}
