<?php

namespace BirdBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * TaxrefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxrefRepository extends EntityRepository
{
}
